### ISSUE TITLE
Unable to Extract Both IPv4 and IPv6 Gateways from Inventory Using Labelpicker Configuration

### ISSUE THREAD

**Issue by dtuecks** [automation-monitoring/labelpicker#3]
Hello,

I am trying to extract both the IPv4 and IPv6 gateways from my inventory. My inventory data looks like this:

```
"routes": {
    "Attributes": {},
    "Nodes": {},
    "Table": {
        "KeyColumns": [
            "gateway",
            "target"
        ],
        "Rows": [
            {
                "device": "eth0",
                "gateway": "192.168.122.2",
                "target": "0.0.0.0/0",
                "type": "gateway"
            },
            {
                "device": "eth0",
                "gateway": "fda7:7bb4:37a3:ffff::2",
                "target": "0.0.0.0/0",
                "type": "gateway"
            }
        ]
    }
}

```
I have tried the following labelpicker configuration:

```
- labelname: v6_gateway
  table_row_mapping:
    routes: [target, gateway]
  tree: [networking, routes, 0.0.0.0/0]
  regex_value_filter: (:)

- labelname: v4_gateway
  table_row_mapping:
    routes: [target, gateway]
  tree: [networking, routes, 0.0.0.0/0]
  regex_value_filter: (\.)
```
  
The idea is that if the gateway value contains a ".", it should be the IPv4 gateway, and if it contains a ":", it should be the IPv6 address. On Dualstack systems, this should result in two labels per host. However, I am only able to retrieve the IPv4 gateway.

Could you please guide me on how to correctly configure the labels to extract both the IPv4 and IPv6 gateways?

Thank you!
