### ISSUE TITLE
Possible to extend documentation

### ISSUE THREAD

**Issue by andersblomgren** [automation-monitoring/labelpicker#4]
Hi,

First of all, great checkmk plugin. I have managed to set host labels based on Software->Operating System->Name 

  Hardware-Software-Inventory:
    module: lpds_hwswtree
    # CMK Label = <label_prefix>/<label>
    # Example label_name: hwsw/os_name
    label_prefix: auto
    mapping:
      - labelname: os
        tree: [Software, Operating System, Name]
        match_group_filters:
          - ['Microsoft Windows Server ([0-9]+).*', 'windows\1']
          - ['Red Hat Enterprise Linux ([0-9]+).*', 'rhel\1']
          - ['Red Hat Enterprise Linux Server release ([0-9]+).*', 'rhel\1']
          - ['Rocky Linux ([0-9]+).*', 'rocky\1']
          - ['Ubuntu ([0-9]+).*', 'ubuntu\1']

Works great! 

But I don't really understand the documentation when it comes to using the inventory with software packages, I don't get it to work either. 

An example, I want to add  the label auto/db:mssql if I can find Microsoft SQL Server 1.* in among the software packages. The sql server installations in my environment seems to be represented in the software inventory as:

Microsoft SQL Server 10
Microsoft SQL Server 11
Microsoft SQL Server 12
Microsoft SQL Server 13
Microsoft SQL Server 14
Microsoft SQL Server 15
Microsoft SQL Server 16 

![Image](https://github.com/user-attachments/assets/0e18e613-5a4c-43ae-baa5-3166b875972c)

My not working config:
     - labelname: db
        table_row_mapping:
          packages: [name, name]
        tree:
          - Software
          - Packages
          - (?i)(Microsoft SQL Server)
        match_group_filters:
          - ['(?i)Microsoft SQL Server 1.*', 'mssql']

Is is possible to extend the documentation with more examples? Or maybe som help in my certain case?

Best regards,
Anders Blomgren

**Comment by PhilippLemke** [comment]
Hi Anders,
I'm glad you like the plugin.
It should be possible to reach this behaviour as described in the docs for the webserver.

https://labelpicker.mk/datasources/lpds_hwswtree/#examples

Modified for MSSQL it should look like this
```yaml
      - labelname: db_mssql
        match_group_filters:
          - ['.*', 'true']
        tree:
          - Software
          - Packages
          - (?i)(Microsoft SQL Server 1)
```

If an HWSW entry with the Regex `Microsoft SQL Server 1` matches (case insensitive -> maybe not necessary) the Value `Microsoft SQL Server 2022 (64bit)` will be replaced by a simple "true"

That should result in a label `hwsw/db_mssql:true` for all the servers with such a HW/SW entry
```text
Microsoft SQL Server 10
Microsoft SQL Server 11
Microsoft SQL Server 12
Microsoft SQL Server 13
Microsoft SQL Server 14
Microsoft SQL Server 15
Microsoft SQL Server 16
```

-> not tested

Best Rg,
Philipp

**Comment by PhilippLemke** [comment]
Also important: Please use the current version from GitHub. I still need to update the MKP on https://exchange.checkmk.com ...

**Comment by andersblomgren** [comment]
Hi Philipp,

Thanks for you quick response. I have upgraded from 1.09 to the 1.10 version of the MKP file and tried with your syntax, unfortenatly it is still not working for me. 

Is it possible to add a flag when running the labelpicker so it gives debug info, for example what data it actually is working with?

My best guess right now is that it maybe is looking in the wrong column of the software.packages table?


Below you can see screens of the software.packages table from one of  the hosts that I believe should have been handled by labelpicker but didn't. 

![Image](https://github.com/user-attachments/assets/dd30196b-2ff2-4788-b55b-aa6de3b6185e)

![Image](https://github.com/user-attachments/assets/f05aa6f6-8359-4284-8a10-0c821d1610ea)

Best regards,
Anders Blomgren

**Comment by PhilippLemke** [comment]
In my tests the problem was the empty value in the mapping name, version. But since you had already used the "correct" term `name, name` that should be not the problem.

The following config works fine on my test instance, please give it a try.

```yaml
datasources:
  # Datasource: CMK-Inventory
  Hardware-Software-Inventory:
    module: lpds_hwswtree
    # CMK Label = <label_prefix>/<label>
    # Example label_name: hwsw/os_name
    label_prefix: hwsw

    table_row_mapping:
      #packages: [name, version]
      packages: [name, name]
      routes: [target, gateway]
      interfaces: [index, speed]
      modules: [ manufacturer, name]
      
     # all MSSQL Servers with the Version 1x will be labeled with db/mssql:true
      - labelname: db/mssql
        match_group_filters:
          - ['.*', 'true']
        tree:
          - Software
          - Packages
          - '(?i)Microsoft SQL Server 1'

      # all MSSQL Servers with the Version 1x will be labeled with db/mssql/version:Microsoft SQL Server 1x
      - labelname: db/mssql/version
        tree:
          - Software
          - Packages
          - '(?i)Microsoft SQL Server 1'
```


![Image](https://github.com/user-attachments/assets/48d8d87c-bc4f-4505-a2f3-f8286116f86a)
